export const categoryImages = [
    { id: 1, image: "/category/category01.png" },
    { id: 2, image: "/category/category02.png" },
    { id: 3, image: "/category/category03.png" },
    { id: 4, image: "/category/category04.png" },
    { id: 5, image: "/category/category05.png" },
    { id: 6, image: "/category/category06.png" },
    { id: 7, image: "/category/category07.png" },
    { id: 8, image: "/category/category08.png" },
    { id: 9, image: "/category/category09.png" },
    { id: 10, image: "/category/category10.png" },
    { id: 11, image: "/category/category11.png" },
    { id: 12, image: "/category/category12.png" },
    { id: 13, image: "/category/category13.png" },
    { id: 14, image: "/category/category14.png" },
    { id: 15, image: "/category/category15.png" },
    { id: 16, image: "/category/category16.png" },
    { id: 17, image: "/category/category17.png" },
    { id: 18, image: "/category/category18.png" },
  ];