export const dealOfTheDay = [
  {
    id: 1,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 4,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
  {
    id: 2,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 3.5,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
  {
    id: 3,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 1.5,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
  {
    id: 4,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 3,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
  {
    id: 6,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 5,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
  {
    id: 7,
    name: "Croma 20000 mAh 22.5W Fast Charging Power Bank (2 Type A, 1 PD Type C & 1 Micro USB Port, Aluminium Casing, Apple Compatible, Black)",
    price: 2400,
    image: '/deal-of-the-day/dealsOfTheDay1.png',
    discountedPrice: 1799,
    rate: 2.5,
    totalRating: 30,
    totalReview: 26,
    keyFeatures: [
      "Battery: 20000 mAh, Lithium Polymer",
      "Fast Charging: Yes, 22.5 W",
      "Power Input Port: PD Type C & Micro USB",
      "Power Output Port: 2 Type A & 1 Type C PD",
      "Cable Included: Yes, USB Type C",
      "Durable Aluminium Housing, Short-Circuit Protection",
      "18 Months Warranty",
    ],
    category: "Mobile & Mobile Accessories",
  },
];


export const getProductFromId = (productId:string) => {
  const product = dealOfTheDay.find(p => p.id === +productId);
  return product;
}
