import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { auth } from "@/auth";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
          <div className="flex flex-col h-screen">
            <div className="sticky top-0 w-full z-50 bg-black ">
              <Header />
            </div>
            <div className="bg-primary-dark flex-1">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}